# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CopiaCli < Formula
  desc "CLI for Copia — source control for industrial automation"
  homepage "https://github.com/qubernetic/copia-cli"
  version "1.0.0"
  license "AGPL-3.0"

  on_macos do
    url "https://github.com/qubernetic/copia-cli/releases/download/v1.0.0/copia-cli_1.0.0_darwin_all.tar.gz"
    sha256 "734506d5fcb50e7c49f8b442fe5ccfc9a7dcd29ba6afb1579aed5d0161c4b4d8"

    define_method(:install) do
      bin.install "copia-cli"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/qubernetic/copia-cli/releases/download/v1.0.0/copia-cli_1.0.0_linux_amd64.tar.gz"
      sha256 "6ec094fc59dcf796e2574fd5144da08cd752ddc4363fc41bc889e6cd745eb8c0"
      define_method(:install) do
        bin.install "copia-cli"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/qubernetic/copia-cli/releases/download/v1.0.0/copia-cli_1.0.0_linux_arm.tar.gz"
      sha256 "e4bd44a4ddfe0fb667ca6fac4391bf76d010bfb585ab0972a9ffba5947849852"
      define_method(:install) do
        bin.install "copia-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/qubernetic/copia-cli/releases/download/v1.0.0/copia-cli_1.0.0_linux_arm64.tar.gz"
      sha256 "a485c6e320dc0b1e7e49bf58e9da3574f891975f43ad9b3ff31b9e558c6a4abb"
      define_method(:install) do
        bin.install "copia-cli"
      end
    end
  end

  test do
    system "#{bin}/copia-cli", "--version"
  end
end
