# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CopiaCli < Formula
  desc "CLI for Copia — source control for industrial automation"
  homepage "https://github.com/qubernetic/copia-cli"
  version "1.1.2"
  license "AGPL-3.0"

  on_macos do
    url "https://github.com/qubernetic/copia-cli/releases/download/v1.1.2/copia-cli_1.1.2_darwin_all.tar.gz"
    sha256 "7594fdc0f6bbcd17faa9551a6d180eab625842a18f62683da7a0742ac9ac1b23"

    define_method(:install) do
      bin.install "copia-cli"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/qubernetic/copia-cli/releases/download/v1.1.2/copia-cli_1.1.2_linux_amd64.tar.gz"
      sha256 "36c94736a11b8190e640089788138d3fcd6fdf2c896b46a92a7b4c41cbe14868"
      define_method(:install) do
        bin.install "copia-cli"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/qubernetic/copia-cli/releases/download/v1.1.2/copia-cli_1.1.2_linux_arm.tar.gz"
      sha256 "3fe56eeca2b3fca71afb4f8ba0815f09ade3390e648466c9faa055f277f634f6"
      define_method(:install) do
        bin.install "copia-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/qubernetic/copia-cli/releases/download/v1.1.2/copia-cli_1.1.2_linux_arm64.tar.gz"
      sha256 "194c62144bbaa3bcfcfd78cd73ec4d378cbf64e4e499b9cae142e200bd517d61"
      define_method(:install) do
        bin.install "copia-cli"
      end
    end
  end

  test do
    system "#{bin}/copia-cli", "--version"
  end
end
