# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Copia < Formula
  desc "CLI for Copia — source control for industrial automation"
  homepage "https://github.com/qubernetic-org/copia-cli"
  version "0.2.0-beta.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/qubernetic-org/copia-cli/releases/download/v0.2.0-beta.1/copia_0.2.0-beta.1_darwin_amd64.tar.gz"
      sha256 "ce7befcedc8ff4ebd684d248095ad3313abbe9bb1d7f35d5b412c40468b5952f"

      define_method(:install) do
        bin.install "copia"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/qubernetic-org/copia-cli/releases/download/v0.2.0-beta.1/copia_0.2.0-beta.1_darwin_arm64.tar.gz"
      sha256 "af4c38ea3915cbc6d4667cd4045710f6e5802e73e98ed3f060a3e6c2939d8f79"

      define_method(:install) do
        bin.install "copia"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/qubernetic-org/copia-cli/releases/download/v0.2.0-beta.1/copia_0.2.0-beta.1_linux_amd64.tar.gz"
      sha256 "b2c682f9daa3ce3ad0009974347db3b98d9b8b45e869095faaaca98513d17dcf"
      define_method(:install) do
        bin.install "copia"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/qubernetic-org/copia-cli/releases/download/v0.2.0-beta.1/copia_0.2.0-beta.1_linux_arm64.tar.gz"
      sha256 "4871458c41649544f1bd0c5ec1438c916d102948ad4bdeb293d6c359e790eebe"
      define_method(:install) do
        bin.install "copia"
      end
    end
  end

  test do
    system "#{bin}/copia", "--version"
  end
end
